### ISSUE TITLE
Cannot create DART job, getting JS error

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/dart_digitization#4]
With some modifications, I've copied [DART's example Python code](https://aptrust.github.io/dart-docs/users/scripting/) into [BagCreator class](https://github.com/RockefellerArchiveCenter/dart_digitization/blob/4482c754b5a2caf1a5e3725ac4c669209c954435/create_bags/bag_creator.py#L61). I've tried to run this locally using Python interactively, and pointing to my local DART installation, but am getting an error that appears to be thrown by JavaScript:

```
>>> cmd = "{} -- --stdin".format(dart_command)
>>> child = Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, close_fds=True)
>>> child.communicate(json_input)
(node:31362) UnhandledPromiseRejectionWarning: TypeError: (this.getValue(...) || "").replace is not a function
    at TagDefinition.toFormattedString (/Applications/DART.app/Contents/Resources/app.asar/bagit/tag_definition.js:242:43)
    at BagItProfile.getTagFileContents (/Applications/DART.app/Contents/Resources/app.asar/bagit/bagit_profile.js:460:31)
    at Bagger._addTagFiles (/Applications/DART.app/Contents/Resources/app.asar/bagit/bagger.js:222:35)
    at Bagger.create (/Applications/DART.app/Contents/Resources/app.asar/bagit/bagger.js:175:24)
(node:31362) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31362) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bonniegordon/opt/anaconda3/envs/env/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/bonniegordon/opt/anaconda3/envs/env/lib/python3.7/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/Users/bonniegordon/opt/anaconda3/envs/env/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
```

I do not run into this error when running DART on the command line. Would appreciate a second look to make sure I'm not doing something wrong before filing an issue in the DART repository.

**Comment by helrond** [comment]
The only thing that gives me some 🤔 in your code is that `encode` on line 63. I wonder if that's munging your JSON string?

**Comment by bonniegee** [comment]
This is what happens when I don't call `encode`:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bonniegordon/opt/anaconda3/envs/env/lib/python3.7/subprocess.py", line 964, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Users/bonniegordon/opt/anaconda3/envs/env/lib/python3.7/subprocess.py", line 1695, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
```
It's why I initially put it there + I just reproduced this. Not sure if I should be dealing with that another way?

**Comment by helrond** [comment]
Two things: 
- the `self.dart_command` attribute looks like it's not set correctly.
- I would try printing out the `job_params` to see what's going on there.

**Comment by bonniegee** [comment]
Okay, I tried re-running on the command line with the JSON produced and realized this was introduced when I added in the Rights-ID tag at the same time. My JSON included numbers, not strings--which is what is causing this error.

This is an easy fix, but I'm not sure if this constraint by DART is necessary/intentional?

**Comment by helrond** [comment]
That is a question you'd have to put to Andrew - I don't know enough about the internals of the application to have a useful opinion...
