### ISSUE TITLE
Clean up copies of files after successful process

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/dart_digitization#7]
This process makes two copies of files that are bagged. Copies should be deleted when the process is successful.

**Comment by bonniegee** [comment]
The copy of files that are initially created (before DART is run) are now deleted via a helper function. However, the created bags are not deleted--I want to test a bit with the S3 upload to see exactly how this would work. We may want to include a test to make sure the bag is in S3, and then delete.

**Comment by helrond** [comment]
If it's useful, there's an `object_in_bucket` helper in the `iiif_pipeline` codebase.
